nk:
  steps:
    check_references:
      label: "Check references"
      index: 30
      commands:
        get_references:
          label: "Get referenced files"
          path: "silex_nuke.commands.get_references.GetReferences"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values:
              value: !command-output "check_references:get_references:file_paths"
              hide: true
            actions:
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"
    conform_references:
      label: "Check references"
      index: 40
      commands:
        repath_attributes:
          label: "Repath attributes"
          path: "silex_nuke.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes:
              value: !command-output "check_references:get_references:attributes"
              hide: true
            values:
              value: !command-output "check_references:conform_references"
              hide: true

    export:
      label: "Export"
      index: 50
      commands:
        export_hip:
          label: "Export as nk"
          path: "silex_nuke.commands.save.Save"
          parameters:
            file_path:
              value: !command-output "setup:build_output_path:full_path"
              hide: true
