save:
  hide: True
  thumbnail: "save.svg"
  steps:
    save:
      label: "Save"
      index: 50
      commands:
        build_work_path:
          path: "silex_client.commands.build_work_path.BuildWorkPath"
          parameters:
            increment: True
        save_scene:
          path: "silex_nuke.commands.save.Save"
          parameters:
            file_path: !command-output "save:build_work_path"
